import { Inter, Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/Components/Navbar";

const inter = Inter({ subsets: ["latin"] });
const poppins = Poppins({weight:['100', '200', '300'], subsets: ["latin"] });

export const metadata = {
  title: {
    default: "Next hero",
    template: "%s | Next Hero"
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Navbar></Navbar>

        {children}
  
        </body>
    </html>
  );
}
